name: Send Dark Tweets

on:
  schedule:
    - cron: '0 9 * * 4'  # 9 AM UTC on Mon and Thu
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Send Tweets
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        BASE_URL: ${{ secrets.BASE_URL }}
      run: python sendTweet.py